version: '3'
services:

  mysqldb:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_PASSWORD: kemane
      MYSQL_ROOT_PASSWORD: kemane
      MYSQL_DATABASE: db_assiduite
    restart: always

  assiduite:
    image: zencaisse:docker_tag
    restart: always
    ports:
      - 8090:8090
    depends_on:
      - mysqldb
    links:
      - mysqldb
    environment:
      DB_HOST: mysqldb:3306
      DB_NAME: db_zencaisse
      DB_USERNAME: root
      DB_PASSWORD: kemane
