spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  thymeleaf:
    suffix: .html
    prefix: classpath:/pages/
  datasource:
    url: jdbc:mysql://localhost:3306/assiduite?createDatabaseIfNotExist=true
    username: root
    password: kemane
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 8088
