spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  thymeleaf:
    suffix: .html
    prefix: classpath:/pages/
  datasource:
    url: jdbc:mysql://localhost:3306/assiduite
    username: root
    password: kemane
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
