spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  thymeleaf:
    suffix: .html
    prefix: classpath:/pages/
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost:3306}/${DB_NAME:assiduite}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:kemane}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8090
